version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: gpds-postgres
    environment:
      POSTGRES_DB: gpds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "202580"
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - gpds-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  mongo:
    image: mongo:7
    container_name: gpds-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gpds-net
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\""]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: gpds-app
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: postgres,mongo
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gpds
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "202580"
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/gpds
    ports:
      - "8081:8080"
    networks:
      - gpds-net

volumes:
  pg_data:
  mongo_data:

networks:
  gpds-net:
    driver: bridge
    external: true
